FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore WebsiteHealthMonitor/WebsiteHealthMonitor.csproj

RUN dotnet publish WebsiteHealthMonitor/WebsiteHealthMonitor.csproj \
    -c Release \
    -o /app/publish \
    --no-restore


FROM mcr.microsoft.com/playwright/dotnet:v1.63.0-noble

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://0.0.0.0:${PORT}

ENTRYPOINT ["dotnet", "WebsiteHealthMonitor.dll"]
